version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8888:8888"

    volumes:
      - .:/demogee
    command:
      - sh
      - -c
      - /bin/sh -c "/demogee/run_jupiter.sh"